userName: ${BROWSERSTACK_USERNAME}
accessKey: ${BROWSERSTACK_ACCESS_KEY}

framework: pytest

platforms:
  - os: Windows
    osVersion: "10"
    browserName: Chrome
    browserVersion: latest

  - os: Windows
    osVersion: "10"
    browserName: Firefox
    browserVersion: latest

  - os: Windows
    osVersion: "10"
    browserName: Edge
    browserVersion: latest

  - os: OS X
    osVersion: Ventura
    browserName: Safari
    browserVersion: latest

parallelsPerPlatform: 1

browserstackLocal: false

buildName: task4-cross-browser
projectName: PRODIGY-ST-02

networkLogs: true
consoleLogs: info
